### ISSUE TITLE
ponder::Value's comparison operators are not complete

### ISSUE THREAD

**Issue by shierei** [billyquith/ponder#105]
The comparison operators include ==, !=, >, <, >=, <=. ponder::Value only overloads operator == and <. Camp works on all of them because camp::Value inherits boost::totally_ordered. I guess the way to work around this for ponder::Value is to  overload all comparison operators.

I also find out that ponder::Value's implicit type conversion , i.e. the template method 'operator T()' does not do implicit type conversion for some reason. Camp can convert just fine but I do not know where the problem is from.

**Comment by shierei** [comment]
The reason that ponder::Value does not do implicit type conversion is because it does not implement 'operator T()'. Is there a reason not to implement it?

**Comment by billyquith** [comment]
> The comparison operators include ==, !=, >, <, >=, <=. ponder::Value only overloads operator == and <. 

You can implement all of the other comparisons with the 2 supplied. We could add more though.

> The reason that ponder::Value does not do implicit type conversion is because it does not implement 'operator T()'. Is there a reason not to implement it?

I removed it because I consider it bad programming practice. Implicit conversion can do some inadvertent/inefficient work if not understood.
